---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# gglobalclocks


```{r, comment=""}
library(tidyverse)
library(lubridate)

ymd_hms("2023-09-02 09:00:00", 
        tz = "America/New_York") ->
  meeting

time_to_local <- function(x, tz){
  lubridate::with_tz(x, tz = tz) %>%
    as.character()
}


OlsonNames() %>%
  tibble(tz = .) %>%
  filter(tz != "US/Pacific-New") %>%
  filter(tz %>% str_detect("Amsterdam|Adelaide|Stockholm|US/Eastern|British|Europe/London|US/Pacific|Mountain|US/Central|Sydney|Europe/Vienna")) %>%
  mutate(meeting_ny = meeting) %>%
  mutate(local_time = purrr::map2(meeting_ny, tz, time_to_local))  %>%
  unnest(local_time) %>%
  group_by(local_time) %>%
  summarise(locations = paste(tz, collapse = "\n")) %>% 
  mutate(day = as_date(local_time) %>% wday(label = T)) ->
df; df

# df %>% 
#   ggplot() + 
#   facet_wrap(~locations) +
#   aes(angle = local_time %>% lubridate::hour() %% 12, 
#       radius = 1, x = 0, y = 0) +
#   geom_spoke(radius = .8) + 
#   geom_spoke(aes(angle = local_time %>% lubridate::minute() %% 60)) 
  

  
df %>% 
  mutate(minute_turn = local_time %>% lubridate::minute() %% 60 / 60) %>% 
  mutate(hour_turn = local_time %>% lubridate::hour() %% 12/12 + minute_turn/12) %>% 
  mutate(am_pm = ifelse(local_time %>% lubridate::hour() > 12, "pm", "am")) %>% 
  ggplot() + 
  facet_wrap(~locations) + 
  aes(x =  hour_turn, 
      xend =  hour_turn,
      y = 0,
      yend = .6,
      color = am_pm) + 
  labs(color = NULL) +
  geom_segment() + 
  geom_segment(aes(x =  minute_turn, 
                  xend =  minute_turn ,
               yend = 1) ) + 
  coord_polar() + 
  scale_x_continuous(limits = c(0,1)) + 
  geom_text(data = tibble(x = 1:12, y = 1), 
            aes(label = x, x = x/12, y = y, xend = NULL, 
                yend = NULL, color = NULL),
            show.legend = F) + 
  theme_void() + 
  annotate(geom = "segment", x = 0, xend = 1, y = 1.2, yend = 1.2)

```

What would gglobalclocks syntax look like using above approach as jumping off point?


```
gglobalclocks() + # wraps up theme void and coord_polar 
 stamp_clockface() + # wraps up drawing numbers and circle
 aes(local_date_time = date_timevar) + 
 geom_clockhands() + 
 facet_wrap(~location)
```
 

```{r}
gglobalclocks <- function(data = NULL){
  
  ggplot(data) + 
  list(theme_void(),
       coord_polar(),
       scale_x_continuous(limits = c(0,1)),
       scale_y_continuous(limits = c(0,1.3)))
  
}

gglobalclocks()

stamp_clockface <- function(){
  
    list(geom_text(data = tibble(x = 1:12, y = 1), 
            aes(label = x, x = x/12, y = y, xend = NULL, 
                yend = NULL, color = NULL, local_time = NULL),
            show.legend = F),
          annotate(geom = "segment", x = 0, xend = 1, y = 1.2, yend = 1.2)
         
    )
  
}

gglobalclocks() + stamp_clockface()

compute_clock_hands <- function(data){
  
  data |> 
  mutate(minute_turn = local_time %>% lubridate::minute() %% 60 / 60) |> 
  mutate(hour_turn = local_time %>% lubridate::hour() %% 12/12 + minute_turn/12) |>  
  mutate(am_pm = ifelse(local_time %>% lubridate::hour() > 12, "pm", "am")) 
  
}

compute_hour_hand <- function(data, scales){
  
  data |>
    compute_clock_hands() |>
    mutate(x =  hour_turn, 
      xend =  hour_turn,
      y = 0,
      yend = .6)
  
}

compute_minute_hand <- function(data, scales){
  
  data |>
    compute_clock_hands() |>
    mutate(x =  minute_turn, 
      xend =  minute_turn,
      # color = am_pm, 
      y = 0,
      yend = 1)
  
}

df |> compute_clock_hands()
df |> compute_minute_hand()


statClockminhand <- ggproto(`_class` = "statClockminhand",
                          `_inherit` = ggplot2::Stat,
                          # required_aes = c("local_time"),
                          compute_group = compute_minute_hand,
                          default_aes = ggplot2::aes(color =
                                                            ggplot2::after_stat(am_pm))
                           )

geom_minute_hand <- function(
  mapping = NULL,
  data = NULL,
  position = "identity",
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = statClockminhand,  # proto object from step 2
    geom = ggplot2::GeomSegment,  # inherit other behavior
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}

statClockhourhand <- ggproto(`_class` = "statClockhourhand",
                          `_inherit` = ggplot2::Stat,
                          # required_aes = c("local_time"),
                          compute_group = compute_hour_hand,
                          default_aes = ggplot2::aes(color =
                                                            ggplot2::after_stat(am_pm))
                           )

geom_hour_hand <- function(
  mapping = NULL,
  data = NULL,
  position = "identity",
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = statClockhourhand,  # proto object from step 2
    geom = ggplot2::GeomSegment,  # inherit other behavior
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}

gglobalclocks(data = df) + 
  aes(local_time = local_time) + 
  stamp_clockface() + 
  geom_minute_hand() +
  geom_hour_hand() + 
  facet_wrap(~locations) 

geom_clock_hands <- function(...){
  
  list(geom_hour_hand(...),
       geom_minute_hand(...))
  
  
}

gglobalclocks(data = df) + 
  aes(local_time = local_time) + 
  stamp_clockface() + 
  geom_clock_hands() + 
  facet_wrap(~locations) 


```
